### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by bfunkhouser** [imdone/imdone-atom#10]
### *Note: it throws this error but still appears to work.*

To Reproduce:
1. Write a comment, e.g. "#doing:20 Task in a text file like markdown" (in a .md file)
2. Save the file (throws this error)

**Atom Version**: 1.0.5
**System**: Microsoft Windows 10 Pro
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.10

### Stack Trace

Uncaught TypeError: Cannot read property 'push' of undefined

```
At C:\Users\bfunkhouser\.atom\packages\imdone-atom\node_modules\imdone-core\lib\repository.js:405

TypeError: Cannot read property 'push' of undefined
    at C:\Users\bfunkhouser\.atom\packages\imdone-atom\node_modules\imdone-core\lib\repository.js:405:19
    at C:\Users\bfunkhouser\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:86:11
    at C:\Users\bfunkhouser\.atom\packages\imdone-atom\node_modules\imdone-core\lib\tools.js:220:24
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
     -0:09.8.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
     -0:03.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:02.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "pen-paper-coffee-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
imdone-atom, v1.1.10
pen-paper-coffee-syntax, v0.9.1

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Fixed by modifying uri with encodeURIComponent

**Comment by bfunkhouser** [comment]
Hooray!  Thanks!

**Comment by playtocrazy** [comment]
Hello, I still got the same error message, 
does this issue be fixed? or what should I do to fix it? 
thank you.
