### ISSUE TITLE
As a user I would like a clean and intuitive UX on imdone.io

### ISSUE THREAD

**Issue by piascikj** [imdone/imdone-atom#108]
Pages
----

- homepage
- pricing page
- checkout page
- account page
- login page

**Comment by piascikj** [comment]
Pages
----

- homepage
- pricing page
- checkout page
- account page

**Comment by kcschmi** [comment]
@piascikj : Should Jake be assigned to this user story? is this mainly what he's working on?

**Comment by piascikj** [comment]
Yes!
