### ISSUE TITLE
Support for Filters Such as "/abc" and "#abc"

### ISSUE THREAD

**Issue by bdsexton** [imdone/imdone-atom#13]
It would be nice to be able to filter the items in lists, either in list settings or live, by things such as "/abc" (a common way to sign messages) and "#abc".

**Comment by piascikj** [comment]
Live filters are available.  Just click on the tools icon.  There you can filter with regular expression.  Another trick I've used is to have a list of filters as mentioned here... [iMDone — iMDone task filters](http://blog.imdone.io/post/108870739920/imdone-task-filters)
