### ISSUE TITLE
Syntax help link makes atom unresponsive

### ISSUE THREAD

**Issue by hobofan** [imdone/imdone-atom#14]
Clicking on the syntax help link in imdone window freezes atom and a "Editor is not responsive. Do you want to force close it" window pops up.

There doesn't seem to be anything special about my project. It's not very big and there were ~10 TODOs correctly loaded.

**Comment by piascikj** [comment]
The syntax help link is an external link.  This sounds like an os issue.  Do you have a default browser set up?  If you open a markdown file, do web links work?  What OS are you running?

**Comment by hobofan** [comment]
Yup, you're right. Some other links in Atom also cause freezes for me, but I didn't make the connection.
