### ISSUE TITLE
Support additional tags (such as feature and bug)?

### ISSUE THREAD

**Issue by mikeerickson** [imdone/imdone-atom#166]
Is there a way to expand the tags which are supported (currently seems only `todo`, `fixme, `review`, and `note`)

Looking to also support `feature` and `bug` tags

**Comment by piascikj** [comment]
Just add it to the board using the "+" button.  If the token isn't all upper case letters you'll have to prefix it with a `#` like this.
```javascript
// #feature: This is a feature
```

But a better way to do this would be to use tags like `+feature`.
```javascript
// TODO: Add that cool button +feature
```

Check out the [syntax page](https://github.com/imdone/imdone-core#task-formats)
