### ISSUE TITLE
.imdoneignore

### ISSUE THREAD

**Issue by juando** [imdone/imdone-atom#17]
So how this works?
i made a ".imdoneignore" file placed in the root of wordpress then added 

```wp-admin/
wp-content/languages/
wp-content/plugins/
wp-includes/
```

but nothing happened i placed it in `".imdone"` and nothing.
Am i missing something? (i updated the package btw)

i forgot to say, i don't want to see wordpress TODO's just mines.

**Comment by piascikj** [comment]
.imdoneignore belongs in the root of your project.  I think the issue you're having may be syntax.

leave off the trailing /

**Comment by adamellsworth** [comment]
What's the correct syntax?

```
./node_modules
node_modules
node_modules/*
```
etc.

Could there be some examples in the readme for omitting directories and files alike?

**Comment by piascikj** [comment]
@adamellsworth I just added some ignore help to the readme.  The first pattern won't work if you are trying to ignore everything in `public/dist`.  The last two will.
