### ISSUE TITLE
Deprecated selector in `imdone-atom/styles/imdone-atom.less`

### ISSUE THREAD

**Issue by molovo** [imdone/imdone-atom#175]
In `imdone-atom/styles/imdone-atom.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .password-lines .line span.text:before` => `atom-text-editor.editor .password-lines .line span.syntax--text:before`

* `atom-text-editor::shadow .password-lines .line span.text` => `atom-text-editor.editor .password-lines .line span.syntax--text`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by piascikj** [comment]
Thanks @molovo.  I also saw the deprecation warning in Atom Beta.  I followed the suggestion, but it broke my password field.  I'll have to look for another approach to implementing a password field.

**Comment by booc0mtaco** [comment]
bump? Hopefully this won't lead to anything breaking soon, but `imdone` is the last one on my list of plugins that needs updating. Worried they might pull the trigger on some kinda major change.

**Comment by piascikj** [comment]
I took a swipe at this a while back, but working with the text-editor-view and masking isn't trivial.  I may just switch to plain old html input.

**Comment by philoserf** [comment]
Perhaps a look at atom's _automatic translation_ code. That term suggests that they are not just using deprecated code paths.
