### ISSUE TITLE
No GitHub issue created by creator-bots

### ISSUE THREAD

**Issue by kvsm** [imdone/imdone-atom#179]
Atom v.1.11.2

With default creator-bot tags, adding '+enhancement' to a TODO comment does not create and link an issue on GitHub.

![image](https://cloud.githubusercontent.com/assets/1372660/20415640/80d973f2-ad31-11e6-9e05-2f897fb8a1a9.png)

**Comment by piascikj** [comment]
That's not good!  I think there might be an issue with credentials expiring.  I'm looking into it now, but can you try visiting <https://imdone.io/account> and going to the bottom of the page to "unlink" and then "link" your github account?  The try modifying the same todo.  Just add a period or something. and save the file.

**Comment by kvsm** [comment]
Ok, tried that a couple of times but still the same issue. When I change the todo and save, I can see the spinner in the task list spinning, and it stays that way, with the rest of the task list disabled.

**Comment by piascikj** [comment]
@kvsm I've deployed a fix for this.  Trey unlinking and linking your github account again.

**Comment by kvsm** [comment]
Sorted, thanks. :) Nice work btw.
