### ISSUE TITLE
Password is not hash

### ISSUE THREAD

**Issue by Necmttn** [imdone/imdone-atom#181]
http://prntscr.com/d9j97r

i'm also not able to login 😢

**Comment by piascikj** [comment]
DOING: I must have just introduced that bug, trying to fix a deprecation.  There's a patch in 2.0.19 gh:181 +bug +deprecated id:119
    [**styles/imdone-atom.less:539**](https://github.com/imdone/imdone-atom/blob/master/styles/imdone-atom.less#L539)  
@imdone *comment-bot*. Get TODOBOTs to do your work at [imdone.io](https://imdone.io)

**Comment by piascikj** [comment]
DONE: I must have just introduced that bug, trying to fix a deprecation.  There's a patch in 2.0.19 gh:181 +bug +deprecated id:119
      [**styles/imdone-atom.less:539**](https://github.com/imdone/imdone-atom/blob/undefined/styles/imdone-atom.less#L539)  
@imdone *closer-bot*. Get TODOBOTs to do your work at [imdone.io](https://imdone.io)

**Comment by piascikj** [comment]
Hope that made sense to you.  I'm working on making these comments more user friendly.

**Comment by Necmttn** [comment]
Thanks mate ! :)
