### ISSUE TITLE
Duplicate Tasks

### ISSUE THREAD

**Issue by codeitco** [imdone/imdone-atom#186]
Hi,

This may be a question more than an actual issue.

I am starting to use SCSS and when I compile the CSS file from it, imdone gives me duplicate tasks because of the generated file. Is there a way I can easily exclude specific files from showing tasks in imdone? I'm looking to exclude the .CSS only since all my work will be done in the SCSS.

I see you have some exclusion pattern in regex but I don't want to break anything by attempting to insert specific file names.

**Comment by piascikj** [comment]
Maybe try creating an `.imdoneignore` file and adding `*.scss` to it.
