### ISSUE TITLE
Trouble syncing with imdone.io

### ISSUE THREAD

**Issue by isalew** [imdone/imdone-atom#188]
I open `Imdone Atom: Tasks` in Atom, and it inits the `.imdone` folder. 
I log into my imdone.io account, and it says `Syncing 1 Comments. Please wait...`. 

Unfortunately, it just sits there, and never loads. Should the `.imdone` folder already be in my remote repo? I currently have the `.imdone` folder on my `.gitignore` list, but have made no remote pushes since initing Imdone.

![screen shot 2016-12-22 at 7 49 18 pm](https://cloud.githubusercontent.com/assets/967861/21446153/be757742-c87f-11e6-91f2-a338e9d36daf.png)

**Comment by marcus-crane** [comment]
Same issue here as well. I'm not sure if there's any log files that can be provided if you need them?

**Comment by piascikj** [comment]
This isn't good.  Would either of you like to do a google hangout to see if we can track down the problem?

**Comment by piascikj** [comment]
@isalew @marcus-crane Is this working for you now since the latest update?

**Comment by marcus-crane** [comment]
@piascikj Ah, sorry for taking ages to get back to you. I just checked it out and syncing all working fine now when installing the latest version 👍

**Comment by isalew** [comment]
Same here, thanks @piascikj  and @marcus-crane!
