### ISSUE TITLE
Can't capture HTML comments in a PHP file.

### ISSUE THREAD

**Issue by nrwinner** [imdone/imdone-atom#198]
Hi,
I'm writing inline HTML in a PHP file, and imdone isn't pulling in any of my html comments. It is grabbing the PHP comments just fine. 

Example:

   ```
 <body>
        <!-- TODO the title of this page is garbage as we don't have a user menu -->
        <?php require_once "../helpers/header.php" ?>
```

**Comment by piascikj** [comment]
The languages.js in imdone-core didn't have a block comment set for php.  I added it, so it should be working now.

**Comment by nrwinner** [comment]
Works perfectly! Thank you!
