### ISSUE TITLE
Ignore node_modules

### ISSUE THREAD

**Issue by MarkHerhold** [imdone/imdone-atom#21]
I am not sure how to ignore node_modules in my project

my `.imdoneignore` file:
```
node_modules
```

Other full-length path combinations and glob patterns do not work for me either.

**Comment by piascikj** [comment]
node_modules is already ignored in .imdone/config.json and it's strange that it's not working for you.  What OS are you on?  What are the versions of atom and imdone-atom?

**Comment by piascikj** [comment]
is `.imdoneignore` at the root of your project?

**Comment by MarkHerhold** [comment]
OS: Ubuntu 15.04
Atom: 1.0.7 (latest)
imdone: 1.1.24

.imdoneignore is indeed in my root project. I have restarted Atom and retried already, no cigar.

**Comment by MarkHerhold** [comment]
You are correct, node_modules is "ignored" in `./imdone/config.json`
```
  "exclude": [
    "^(node_modules|bower_components|\\.imdone|target|build|dist|logs)[\\/\\\\]?|\\.(git|svn|hg|npmignore)|\\~$|\\.(jpg|png|gif|swp|ttf|otf)$"
  ],
...
```

**Comment by piascikj** [comment]
Can you share the repo of your project, or is it not public?

**Comment by MarkHerhold** [comment]
It is not public. I can try to reproduce on another repo though.

**Comment by piascikj** [comment]
Or send me a snapshot of your atom and imdone issues board.

**Comment by MarkHerhold** [comment]
Ah. Figured it out.

imdone does not ignore node_modules if they reside in any directory but the root directory.
I have a project that has "sub" modules with their own package.json, node_modules, etc.

It looks like I can resolve the issue by adding the submodules' node_modules folder to the .imdoneignore file:
```
submodule/node_modules
```

It would still be nice to not have to specify this for all of my submodules though, i.e. ignore all folders called `node_modules` by default.

**Comment by piascikj** [comment]
I can add that, but you can also try `**/node_modules` in `.imdoneignore`

**Comment by MarkHerhold** [comment]
I like `**/node_modules` better anyway, that way you don't have to come up with a way to undo the base config. Just tried it and it works.

This is really an excellent project by the way, @piascikj 
Very well done. I am super impressed. :+1:

**Comment by piascikj** [comment]
Thanks @MarkHerhold!  If you like it, star it on [the package page](https://atom.io/packages/imdone-atom) and tell your friends.  I'm working on getting it featured.  You can [read more about imdone here](http://blog.imdone.io)

**Comment by MarkHerhold** [comment]
:star:'d!

**Comment by piascikj** [comment]
:100:  :+1:
