### ISSUE TITLE
feature request: plugins for other editors.

### ISSUE THREAD

**Issue by natecox** [imdone/imdone-atom#214]
I love the idea here, but I don't really want to be stuck on Atom to use imdone. Atom is nice and all, but it's not always the best solution; e.g., I use pyCharm for Python/Django and emacs for elixir/Phoenix.

Is there any intention of implementing this elsewhere?

**Comment by piascikj** [comment]
@natecox My plan is to release imdone as a stand alone electron app.  This will allow the developer to use their default editors/IDEs.
