### ISSUE TITLE
"maximum call-size stack exceeded"

### ISSUE THREAD

**Issue by ChristopherVH** [imdone/imdone-atom#217]
I get this error anytime I actually run the command to open the service, IE it's not working at all for me...

**Comment by kinged007** [comment]
#78

**Comment by piascikj** [comment]
Anyone experiencing the range error please try 2.1.20 and let me know if you're still experiencing the issue.  If you are, please attach a fresh stack trace.

**Comment by piascikj** [comment]
Try v2.1.21. I filtered the files before calling async.each. I think it's fixed.
