### ISSUE TITLE
Going to List item opens multiple of the same page.

### ISSUE THREAD

**Issue by dcboy95** [imdone/imdone-atom#225]
I click on the link to go to my TODO, and it will open multiple tabs of the exact same page. At first it was creating 3 more tabs, now it is creating 14.... I've only changed the config file to care for TODO. I've created an ignore file for specific types. I don't know how this is happening

**Comment by piascikj** [comment]
Is it the file link that you're clicking?  Can you attach some screenshots?

**Comment by dcboy95** [comment]
Yes. When I click the link on one of my TODOs to goto the page.
![image1](https://cloud.githubusercontent.com/assets/8877998/24773803/d0efbd0a-1ad3-11e7-9dd2-b1c931afd59d.PNG)
![image2](https://cloud.githubusercontent.com/assets/8877998/24773804/d0f78e90-1ad3-11e7-8394-b2ed9dedf419.PNG)

**Comment by piascikj** [comment]
----

DOING: Fix issue with multiple tabs of sake file opening id:144 gh:225
[**lib/views/imdone-atom-view.coffee:659**](https://github.com/imdone/imdone-atom/blob/master/lib/views/imdone-atom-view.coffee#L659)

@imdone *commenter*. The developer's task board. [imdone.io](https://imdone.io)

**Comment by piascikj** [comment]
----

DOING: Fix issue with multiple tabs of same file opening id:144 gh:225
[**lib/views/imdone-atom-view.coffee:659**](https://github.com/imdone/imdone-atom/blob/master/lib/views/imdone-atom-view.coffee#L659)

@imdone *commenter*. The developer's task board. [imdone.io](https://imdone.io)

**Comment by piascikj** [comment]
----

DOING: Fix issue with multiple tabs of same file opening id:144 gh:225
[**lib/views/imdone-atom-view.coffee:659**](https://github.com/imdone/imdone-atom/blob/master/lib/views/imdone-atom-view.coffee#L659)

@imdone *commenter*. The developer's task board. [imdone.io](https://imdone.io)

**Comment by piascikj** [comment]
DONE  Fix issue with multiple tabs of same file opening gh:225 id:36

----

https://github.com/imdone/imdone-atom/blob/37b70ac8c5cd7c3c1aa9e85712323edc29854b90/lib/views/imdone-atom-view.coffee#L243-L248

**Comment by piascikj** [comment]
@dcboy95 Looks like I got this fixed.  Let me know if you can reproduce the error.  I moved the event listener to the imdone-atom component instead of body.  Not quite sure I had it listening on body 🤓

**Comment by piascikj** [comment]
REVIEW  Fix issue with multiple tabs of same file opening gh:225 id:36

----

https://github.com/imdone/imdone-atom/blob/b7251b7ccf00e69c484ae85d9668078cedb7152e/lib/views/imdone-atom-view.coffee#L243-L248

**Comment by piascikj** [comment]
Issue closed with imdone.io by removing a comment.

----

https://github.com/imdone/imdone-atom/blob/b7251b7ccf00e69c484ae85d9668078cedb7152e/lib/views/imdone-atom-view.coffee#L243-L248
