### ISSUE TITLE
Due date is removed when dragging ToDo from board to board

### ISSUE THREAD

**Issue by Hardaware** [imdone/imdone-atom#226]
When I drag one of my ToDo items from one board to another (say from "New" to "In Progress") the due date parameter is removed from the ToDo item, therefore losing information.

Date formats "yyyy-mm-dd" and "yyyy-dd-mm" present the issue
Tags other than "due:" do not present the issue
Using the tag "Due:" (with a capital D) does not present the issue

I use imdone-atom on plain texst files

**Comment by Hardaware** [comment]
Issue only presents in due:yyyy-mm-dd format --> moving to due:dd-mm-yyyy is a workaround

**Comment by conormce** [comment]
I'm also finding this problem with some additional info
If I move any item from one list to another or inside the same list the due date is removed from that item and all other items with a due date.

**Comment by piascikj** [comment]
Got a fix in the pipeline.  I'll have it published tonight.
