### ISSUE TITLE
Error while watching files: Error: watch 

### ISSUE THREAD

**Issue by sanpoChew** [imdone/imdone-atom#228]
I'm not sure if I'm doing something wrong or if this is a bug, my .imdoneignore file contains
`node_modules/`

my config.json is
`{
  "exclude": [
    "^(node_modules|bower_components|\\.imdone|target|build|dist|logs)[\\/\\\\]?|\\.(git|svn|hg|npmignore)|\\~$|\\.(jpg|png|gif|swp|ttf|otf)$"
  ],
  "watcher": true,
  "keepEmptyPriority": false,
  "code": {
    "include_lists": [
      "TODO",
      "DOING",
      "DONE",
      "PLANNING",
      "FIXME",
      "ARCHIVE",
      "HACK",
      "CHANGED",
      "XXX",
      "IDEA",
      "NOTE",
      "REVIEW"
    ]
  },
  "lists": [],
  "marked": {
    "gfm": true,
    "tables": true,
    "breaks": false,
    "pedantic": false,
    "smartLists": true,
    "langPrefix": "language-"
  }
}`

yet whenever I attempt to scan for tasks I get an error for seemingly every single file (7946 console messages) in the node_modules folder saying the same thing

`/home/joe/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-watched-fs-store.js:107 Error while watching files: Error: watch /home/joe/repos/genesisagency.co.uk/node_modules/vue/src/platforms/weex/runtime/modules/events.js ENOSPC(…)(anonymous function) @ /home/joe/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-watched-fs-store.js:107
`

Is this something I've done wrong?

**Comment by piascikj** [comment]
What OS and version of atom are you running?

**Comment by sanpoChew** [comment]
@piascikj I'm on Arch Linux, Atom would've been the latest beta at the time which looking at the releases was 1.17.0. I've since moved on to using Visual Studio Code for most work now so you can probably just close this.
