### ISSUE TITLE
imdone fails to open at all

### ISSUE THREAD

**Issue by liam-b** [imdone/imdone-atom#230]
Hey, I tried to install imdone-atom but I get this error when I try to run it.
`binding@unknown – Cannot find module '/Users/liam/.atom/packages/imdone-atom/node_modules/fsevents/lib/binding'`

Atom version: 1.18.0
imdone-atom: 2.2.6

Please help me!

**Comment by quarterto** [comment]
You can fix this by opening `Incompatible Packages: View` from the Command Palette and clicking Rebuild

**Comment by ozyozyo** [comment]
it works for me.
```
apm clean
apm dedupe
```
