### ISSUE TITLE
IMDONE activation not persisting

### ISSUE THREAD

**Issue by RMBLRX** [imdone/imdone-atom#232]
Every time I close open my project on Atom, IMDONE needs me to activate it again, and I end up with duplicate projects in my IMDONE account.  Also, I thought it possible that this issue relates to the fact that when I create an issue from a TODO, I don't see a link to that issue on the taskboard (i.e., no octicon, just a lightbulb), even though I can see the issue added under the "update linked issue" module.

**Comment by piascikj** [comment]
I'm currently working on a service that integrates your TODOs when you push to github.  Once complete, I'm planning to remove the integration from imdone-atom.  Would this work better for you?

**Comment by RMBLRX** [comment]
Actually, yeah. That sounds pretty solid. Would we still get links to issues in atom after a push? I would still find that useful.

**Comment by RMBLRX** [comment]
My issue seems to be fixed since the last update (I believe, but in any case, it is currently working).  Thanks a lot, and keep up the great work!
