### ISSUE TITLE
How to display new list tasks

### ISSUE THREAD

**Issue by JToward** [imdone/imdone-atom#233]
I have added a newlist called DOCKLIST and added few tasks using hash syntax in .txt and .md files. The DOCKLIST has no item to show in the taskboard page. Did I miss something?

**Comment by robertsck** [comment]
I can confirm I'm having a similar problem. If I create standard lists: TODO, DOING, DONE, etc. They work fine. But if I create something more custom such as: SOMEDAY - then the list does not update. I'm working only in .md files. I'm primarily using hash syntax but tried all syntax styles in testing.

**Comment by piascikj** [comment]
Just fixed this in the latest release.  Reopen if the problem persists.
