### ISSUE TITLE
it is not ended scanning

### ISSUE THREAD

**Issue by yuta0801** [imdone/imdone-atom#234]
scanning is not ended forever in using Electron project.

I try it in other project, then it end scanning.

**Comment by piascikj** [comment]
Try version 2.3.0.  I moved the file watcher to a background process.

**Comment by piascikj** [comment]
Have you tried adding directories to the .imdoneignore file?

**Comment by Jackymancs4** [comment]
I can confirm that with version 2.3.10 the issue is still open.
When opening the Tasks window on any Electron project, Atom silently throw
```
Uncaught TypeError: callback is not a function
    at ELECTRON_ASAR.js:568
    at _combinedTickCallback (internal/process/next_tick.js:67)
    at process._tickCallback (internal/process/next_tick.js:98)
(anonymous) @ ELECTRON_ASAR.js:568
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```
12 times, than it stop keeping the Scanning message and animation running.
I have no .imdoneignore.

**Comment by piascikj** [comment]
Can you point me to a github repo I can reproduce the error on?

**Comment by Jackymancs4** [comment]
https://github.com/Jackymancs4-Fork/browserosaurus
This one is what I was working on when the problem occurred. It has various TODO notations that get succesfully caught by other packages. I'm also been able to reproduce the issue on other Electron boilerplate project, but not other frontend-like repositories.
Note: I noted that the exception is thrown a variable number on times (not always 12)

**Comment by Jackymancs4** [comment]
MacOS 10.13.1
Atom 1.22.1

Following your reply I fresh cloned the repo in a different folder to check what was going on, and yes, everything worked out fine.
But after installing the package and reloading atom, here again the issue occurring.
Please, run ```yarn install``` on the repo, and try again..

**Comment by Jackymancs4** [comment]
@piascikj Out of curiosity, can I get confirmation that the issue is replicable?

**Comment by piascikj** [comment]
Yes it is.  I think I've got a fix.  Working on it now.

On Dec 2, 2017 9:09 AM, "Giacomo Rossetto" <notifications@github.com> wrote:

@piascikj <https://github.com/piascikj> Out of curiosity, can I get
confirmation that the issue is replicable?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/imdone/imdone-atom/issues/234#issuecomment-348701719>,
or mute the thread

**Comment by piascikj** [comment]
Looks like I found the issue.  I replaced node-dir with recursive-readdir.  Try the latest release.

**Comment by Jackymancs4** [comment]
Version 2.3.14 fixes the problem for me, and now the extension work like a charm.
Looking into your commits I see you still use node-dir. Was it just a problem of event handling?

**Comment by piascikj** [comment]
I think it's a problem with the package itself.  I'll be removing it soon.  It was just a late night fix.

Glad it's working for you!
