### ISSUE TITLE
How to create a new task

### ISSUE THREAD

**Issue by TylerL-uxai** [imdone/imdone-atom#235]
I see a plus icon to create a list. Is there a way to create a task using the GUI instead of code?
![badge](https://img.shields.io/badge/points-13-blue.svg?style=for-the-badge)

**Comment by piascikj** [comment]
There's no way to do that outside of the code.  Do you have any thoughts as to where it would live?  What file it would be in?

**Comment by piascikj** [comment]
You can do this with the [project journal](https://github.com/imdone/imdone-atom#project-journal) or [global journal](https://github.com/imdone/imdone-atom#global-journal)
