### ISSUE TITLE
The scaning doesn't look like ending anytime soon.

### ISSUE THREAD

**Issue by yuta0801** [imdone/imdone-atom#236]
The scaning doesn't look like ending anytime soon...

Scan finished as soon as I deleted node_modules with many files.
But I need it...

I created .imdoneignore but it did not improve...
the file content
```
node_modules/
```

Thanks you!

**Comment by piascikj** [comment]
Try version 2.3.0.  I moved the file watcher to a background process.

**Comment by piascikj** [comment]
#234
