### ISSUE TITLE
.imdoneignore not handling paths

### ISSUE THREAD

**Issue by jmgore75** [imdone/imdone-atom#24]
If I specify an .imdoneignore file as follows: 

```
dist
src/admin/config.js
```
then everything in the `dist` directory is ignored as expected, but the `src/admin/config.js`
file's TODOs still show up in the task list.  More generally, any .imdoneignore file entry with a multipart path will not be ignored.  

I am on a windows machine.  On the tasks list, the links to the files have "\" path dividers, not "/".  Is that related? I have tried specifying paths with "\" instead, but it did not fix the problem.

**Comment by piascikj** [comment]
@jmgore75 I'll look into this tonight

**Comment by jmgore75** [comment]
FYI I can ignore files with paths by putting something like `^src\\\\admin\\\\config.js$` in `.imdone/config.json` but that seems kind of roundabout, not to mention sensitive to the filesytem you happen to be working on.

**Comment by piascikj** [comment]
@jmgore75 Can you confirm this is now working correctly in imdone-atom v1.1.33?

**Comment by jmgore75** [comment]
As of v1.1.37 I am still having the same problem.

**Comment by piascikj** [comment]
What version of windows are you running?  I can test again later tonight.  I tested with windows 10 and it worked as expected with forward slashes.

**Comment by jmgore75** [comment]
Windows 7

On Tue, Sep 1, 2015 at 11:12 AM, Jesse Piascik <notifications@github.com>
wrote:

> What version of windows are you running? I can test again later tonight. I
> tested with windows 10 and it worked as expected with forward slashes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/imdone/imdone-atom/issues/24#issuecomment-136755811>.
>



-- 
Sent from GMail

**Comment by piascikj** [comment]
Is this still giving you trouble?  If it is, can you send me your `.imdoneignore` and `.imdone/config.js`
