### ISSUE TITLE
 Also add the task list as a label when creating an issue on github 

### ISSUE THREAD

**Issue by piascikj** [imdone/imdone-atom#242]
Issue opened with imdone.io from code comment on [9f751f1](https://github.com/imdone/imdone-atom/commit/9f751f14f022fed15d90b360e4f50f43250dcb82)

BACKLOG  Also add the task list as a label when creating an issue on github +waffle id:10

----

https://github.com/imdone/imdone-atom/blob/9f751f14f022fed15d90b360e4f50f43250dcb82/lib/plugins/plugin-view.coffee#L100-L105

**Comment by piascikj** [comment]
DOING  Also add the task list as a label when creating an issue on github +waffle id:10 gh:242

----

https://github.com/imdone/imdone-atom/blob/44b9c7651d472506ec8c8c66ccf49260b34949e0/lib/plugins/plugin-view.coffee#L100-L105

**Comment by rollinglow19** [comment]
APPROVED

**Comment by piascikj** [comment]
DOING  Also add the task list as a label when creating an issue on github!!! +waffle id:10 gh:242

----

https://github.com/imdone/imdone-atom/blob/37b70ac8c5cd7c3c1aa9e85712323edc29854b90/lib/plugins/plugin-view.coffee#L100-L105

**Comment by piascikj** [comment]
Issue closed with imdone.io by removing a comment.

----

https://github.com/imdone/imdone-atom/blob/b7251b7ccf00e69c484ae85d9668078cedb7152e/lib/plugins/plugin-view.coffee#L100-L105
