### ISSUE TITLE
Line numbers in issues window are n*2-1 compared to actual line number in code

### ISSUE THREAD

**Issue by Rastem88** [imdone/imdone-atom#25]
It appears that the line numbers in the issues window are incrementing by 2.
![imdonebug](https://cloud.githubusercontent.com/assets/12613318/9476587/0d8e29a8-4b33-11e5-8720-91d181757a57.JPG)

**Comment by piascikj** [comment]
Are you running on windows?

**Comment by Rastem88** [comment]
I am.

**Comment by piascikj** [comment]
@Rastem88 Can you confirm this is now working correctly in imdone-atom v1.1.33?

**Comment by Rastem88** [comment]
It is working correctly. Thanks for the quick update.
