### ISSUE TITLE
tasks stopped to work, I cannot drag or sort tasks

### ISSUE THREAD

**Issue by tbogard** [imdone/imdone-atom#26]
In the most recent update, The task who once were draggable, now are not. 

Windows 10 x64
Atom 1.0.7
imdone-atom 1.1.33

Please help!

**Comment by piascikj** [comment]
I'll have a look today.  Is it on atom restart?  I noticed that myself.

**Comment by tbogard** [comment]
seems after restarting atom it start to work, not sure why. If it freezes again I will let you know

**Comment by piascikj** [comment]
@tbogard This should be fixed in 1.1.34.  Let me know if it happens again.
