### ISSUE TITLE
Export TODOs

### ISSUE THREAD

**Issue by iansoper** [imdone/imdone-atom#27]
I would like to be able to export TODOs. Like copying to a clipboard or exporting to a certain format (markdown, html). Is this something you're considering doing?

**Comment by piascikj** [comment]
I like the idea.  How would you feel about having a configurable [lodash template](https://lodash.com/docs#template)?  I could apply a deep clone of the repository in the context and provide a default template as an example.

**Comment by lordnynex** [comment]
:+1:

**Comment by iansoper** [comment]
Oh, I didn't respond, sorry. Yes, some sort of templating system would be great. A few options out of the  box might be helpful as well.

**Comment by lordnynex** [comment]
For me, in a perfect world, I could export items as github issues. I may just be dreaming though :) Also, if I could pull GH issues, this app would make my day.

**Comment by piascikj** [comment]
@lordnynex I'm working on a plugin for that now.  Stay tuned!

**Comment by jpbourgeon** [comment]
+1
it would be very interesting to export todos in a customizable format :

-   for filing
-   for communication with stakeholders

**Comment by piascikj** [comment]
This has been implemented in 2.4.1.  alt+x creates imdone-export.json.  Make sure you add it to .imdoneignore .

**Comment by piascikj** [comment]
@lordnynex you can create github issues from your TODO comments with [imdone.io](https://imdone.io)
