### ISSUE TITLE
Invalid imdone-core version

### ISSUE THREAD

**Issue by Hufschmidt** [imdone/imdone-atom#272]
Updating imdone-atom currently fails, since there is no `^1.3.35` release for imdone-core. :smiley: 

I think this happened when adding the `ignore`-package
https://github.com/imdone/imdone-atom/commit/50715aa25de6cf9915a8a9535f18da9a7e43d7d7

**Comment by piascikj** [comment]
Thanks!  All fixed up.  I forgot to publish imdone-core. :stuck_out_tongue_winking_eye:
