### ISSUE TITLE
Can't get .imdoneignore or the exclude pattern to work

### ISSUE THREAD

**Issue by eyaleizenberg** [imdone/imdone-atom#285]
I want to completely ignore everything is `src` and `test` for example.

What's the correct setting here?

This is my exclude:
  "exclude": [
    "^(node_modules|bower_components|\\.imdone|target|build|test|dist|logs|flow-typed)[\\/\\\\]?|\\.(git|svn|hg|npmignore)|\\~$|\\.(jpg|png|gif|swp|ttf|otf)$"
  ],

And in the .imdoneignore I've tried every combination like this:
test
test/**
test/**/*
test/*

etc...

**Comment by piascikj** [comment]
Try putting this in your .imdoneignore
```
src
src/**/*
test
test/**/*

```

**Comment by eyaleizenberg** [comment]
@piascikj I did, doesn't work, I get all the TODO from the entire code...

**Comment by piascikj** [comment]
What OS are you running?  Is this a public repo?  If it's not a public repo, can you reproduce the issue on a public one, so I can test?

**Comment by Tokimon** [comment]
I am having the same problem on windows 10 - 64 bit

This is my `.imdoneignore`:
```
_migrations
_workers
_configs
_webpack-backup
configs
storage
libs
pub
public
web/public
uploads
vendors
node_modules
bower_components
uglify-cache
```

all entries are folders but imdone keeps finding tasks in fx `libs`

**Comment by eyaleizenberg** [comment]
@piascikj I am on high sierra. It's a private repo.

**Comment by piascikj** [comment]
interesting and puzzling.  Have you tried using a deny/allow approach like this...
```
*
!included_folder
!included_folder/**/*
```

**Comment by piascikj** [comment]
This might be a stupid question, but is your .imdoneignore in the main project folder?

**Comment by eyaleizenberg** [comment]
@piascikj Yes, it's in the main folder, see image below. I tried what you suggested and it didn't work. I tried even doing just `*` expecting to now get any tasks - that didn't work either...

<img width="503" alt="screen shot 2017-12-07 at 7 26 46" src="https://user-images.githubusercontent.com/1061345/33700141-08d85260-db20-11e7-818c-b0a2172b24c7.png">

**Comment by piascikj** [comment]
I added some debugging and removed some unused logic.   Update to 2.3.16, open your board and select View>Developer>Toggle Developer Tools.  When developer tools opens, there should be console output.  Can you copy and past it here?  It should look something like this...
<img width="1435" alt="screen shot 2017-12-07 at 12 03 04 pm" src="https://user-images.githubusercontent.com/233505/33733346-b9fe8ca0-db46-11e7-806f-c0a9a84a4284.png">

**Comment by Tokimon** [comment]
I have updated to version 2.3.16, but I don't get any debugging information at all :'(

**Comment by eyaleizenberg** [comment]
@piascikj So after upgrading to 2.3.17 the ignore works, however I am not finding the tasks in the non-ignored. This is my `.imdoneignore`

```
*
!imdoneTasks.js
```

In the log which is now printed I see it excluding everything, but not including anything...

![screen shot 2017-12-10 at 16 05 35](https://user-images.githubusercontent.com/1061345/33805580-0516afea-ddc4-11e7-9753-b14b621970f5.png)

**Comment by piascikj** [comment]
what is the path to imdoneTasks.js?

**Comment by eyaleizenberg** [comment]
It's in the root of the project

**Comment by piascikj** [comment]
I don't see it in the log.  What's in the file?

**Comment by Tokimon** [comment]
For latest update works perfectly. Good job :+1:

**Comment by piascikj** [comment]
Thanks @Tokimon

**Comment by piascikj** [comment]
@eyaleizenberg where does imdoneTasks.js live?
