### ISSUE TITLE
TODO items deleted when dragged to a new list

### ISSUE THREAD

**Issue by ggiesa** [imdone/imdone-atom#291]
Dragging from 'TODO' to 'doing' gives me the proper animation and everything, but when I drop the item it disappears completely from the package UI. It does seem to change the '#TODO' to '#Doing' in the code though. 
 
![capture](https://user-images.githubusercontent.com/25808882/34811403-ac3273d8-f6db-11e7-8b61-4ef4e0154a6e.PNG)

I'm using Python 3.6.1 and Atom 1.23.3.
Here are my installed packages:

api-docs@0.0.6
busy-signal@1.4.3
emmet@2.4.3
es6-javascript@1.0.0
gpp-compiler@3.0.7
Hydrogen@2.1.0
imdone-atom@2.3.29
intentions@1.1.5
linter@2.1.0
linter-javac@1.9.4
linter-ui-default@1.1.0
monokai@0.22.0
monokai-shade@0.3.5
monokai-slate@0.6.0
nord-atom-syntax@0.6.0
nord-atom-ui@0.10.2
platformio-ide-terminal@2.5.0
python-debugger@0.2.0
script@3.17.3

**Comment by piascikj** [comment]
Just fixed this up in 2.3.30.  Thanks for reporting.  If you add a list without all caps and move a TODO into that list.  The list will be prepended with a `#`.  SO...
```python
# TODO: rework this code
```
when moved to `Doing` becomes...
```#python
# #Doing: rework this code
```

**Comment by ggiesa** [comment]
Thanks for taking care of this! Love the package, keep up the good work!
