### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by dimensia** [imdone/imdone-atom#3]
Awesome idea!  Unfortunately it's either crashing for me or opening up a blank text editor window.  I have a pretty large project.

**Comment by piascikj** [comment]
How many files in your project?  Are there directories and/or files imdone can ignore?

**Comment by piascikj** [comment]
Can you send me some more details?

**Comment by bdsexton** [comment]
I have seen some crashes too on a project with several thousand files. It might be nice to set the scope of interest on first launch before digging through libraries and such.

**Comment by piascikj** [comment]
@bdsexton I like that idea.  Any ideas for a user experience?

**Comment by roman01la** [comment]
For me Atom hangs almost on every interaction with package's functionality. Is it parsing entire project tree?

**Comment by piascikj** [comment]
I just added support for .imdoneignore.  Soon I will be adding a popup warning to add .imdoneignore when a project has over 1500 files.

**Comment by piascikj** [comment]
Just implemented a failsafe for too many files today.
