### ISSUE TITLE
recent update ignores .imdoneignore

### ISSUE THREAD

**Issue by tbogard** [imdone/imdone-atom#31]
Hello, after update, I'm not able to control atom, it keeps loading all the #todo from my node_modules and is a nightmare now... atom is hanged up to 100% cpu and I can't get edition back. is there a way to remove the package without running atom? thanks.

**Comment by piascikj** [comment]
@tbogard That sucks!  To uninstall, just run `apm uninstall imdone-atom`.  As of 1.1.33, `.imdoneignore` should only have paths with forward slashes, and will work for both *nix/mac and windows.  I tested on windows and linux.  Are you running on a windows machine?

**Comment by tbogard** [comment]
yes, on windows.
after wipping all atom I had to do a lot of extra configurations to make sure i'm getting my tasks.

for example, I detected after I created my electron app on my project folder, that the tasks immediatelly stops to work.

I assume it was looking for notes in the wrong places : in exe files, in app.asar files, etc, I didn't expected atom to behave like this. I had .imdoneignore node_modules and no problem about it,

I guess imdone should let the user what filetypes must select to look for tasks, not for what must ignore, having by default IGNORE ALL FILES. It will be easy to maintain exactly what it needed to be  selected to look into, like "*.js" instead of ignoring a large array of variables : ".git"
      ".hg"
      ".svn"
      ".DS_Store"
      "Thumbs.db"
      ".codekit-cache"
      "bower_components"
      "node_modules"

That is my suggestion to the developer: that by default only accept reading .js files and let the user do a white list of filetypes or locations where the program can crawl for information.

**Comment by piascikj** [comment]
Thanks for the feedback, but I don't think I'll be switching to that model, because it should just work out of the box.  I am willing to get it working with .imdoneignore.  imdone will not look at exe and binary files, but let's try getting this worked out.  What version of windows are you on?  What does your .imdoneignore look like?  What are the paths you want it to ignore?

**Comment by tbogard** [comment]
sure:
win10 Pro x64
My ignore settings are:

* core settings
.git, .hg, .svn, .DS_Store, Thumbs.db, .codekit-cache, bower_components, node_modules

* .imdoneignore (after reading your comment)
node_modules
jquery-*
*-ia32
*-ia64
*.asar
*.exe
*.dll
*.bin
*.pak
*.dat
locales
resources
default_app

iMdone settings:
- checked Exclude vcs ignore paths
Max File prompt : 1000

now, it will be cool for those who develop on electron that certain paths were excluded:

- resources
- win32*
- win64*
- *-ia32
- *-ia64

and this files:

*.asar

since, you know, atom and electron are like brothers.

**Comment by piascikj** [comment]
@tbogard I'm a little confused.  Is your current `.imdoneignore` now working?

**Comment by tbogard** [comment]
right now it works, but I have to be careful to exclude the build folder which contains the binaries.

**Comment by piascikj** [comment]
Great, so I'll close the ticket.
