### ISSUE TITLE
Todo's not recognized in .jsx files 

### ISSUE THREAD

**Issue by enjoylife** [imdone/imdone-atom#34]
Title says it all. Any simple way to resolve?

**Comment by piascikj** [comment]
Sure, You can add...
```javascript
languages: {
  ".jsx":          {"name": "jsx", "symbol": "//", "block": cBlock}
}
```
to `.imdone/config.json` or you could just wait a few minutes and I'll add it to languages.js. :sunglasses:

**Comment by piascikj** [comment]
Done!  It's in 1.1.45.

**Comment by enjoylife** [comment]
Nice, thanks for the update.
