### ISSUE TITLE
Dragging around items stops working after a while

### ISSUE THREAD

**Issue by markvandenbrink** [imdone/imdone-atom#35]
Hi there,

I really like iMDone for Atom, but I have this strange bug. After dragging around some items to a new position (which works fine), the drag-and-drop feature stops working and I end up with just selecting the HTML text of the iMDone page when I try to "grab" an item:

![imdone](https://cloud.githubusercontent.com/assets/7869636/10417895/0975ed0e-704c-11e5-84a5-0abd1d921fa7.jpg)

I have to restart Atom to restore the drag-and-drop functionality. Closing and reopening the iMDone pane is not sufficient. I've checked the Developer console, but there are no error messages. The fact I have to restart Atom may indicate I have another package enabled which conflicts with iMDone. I've already inspected the HTML element of an item and it has listeners attached for dragstart, etc. I can dive deeper into the code behind and try to figure out what's going wrong or what's conflicting. But I was wondering if there are other users which experience the same problem?

I'm using Atom 1.0.19 on Windows (10). Any ideas? Thanks!

**Comment by tony612** [comment]
+1 for OS X 10.10.5 & Atom 1.0.19

**Comment by piascikj** [comment]
@markvandenbrink @tony612 Can you reproduce and tell me when it starts to happen?

**Comment by tony612** [comment]
@piascikj Yeah, I think so. It works for the first time after I restart Atom. But then I can't drag the card any more.

**Comment by piascikj** [comment]
@markvandenbrink @tony612 The latest patch should fix this.  Let me know if it works for you.
