### ISSUE TITLE
As a user I would like to quickly move a card to the bottom/top of a list

### ISSUE THREAD

**Issue by jronallo** [imdone/imdone-atom#365]
Sometimes I have long lists that I'm cycling through as I check some more items off the card and hit a roadblock. Right now I either have to drag the card far down the page to get it put at the end or I have to go into the file and just increase the number ridiculously high. Not awful either way, but it might be nice to have buttons that allow moving a card to the top or bottom with a click.

**Comment by piascikj** [comment]
Great idea Jason!  Maybe a down-arrow for move to bottom and an up-arrow for move to top.

**Comment by piascikj** [comment]
Just implemented this in 2.4.19
