### ISSUE TITLE
Error: Cannot find module 'imdone-core/lib/Repository' (Version 2.4.21)

### ISSUE THREAD

**Issue by dwuttke90** [imdone/imdone-atom#377]
The error shows up if I try to open the task board.

The problem seems to be in the [transform.js](https://github.com/imdone/imdone-atom/blob/master/lib/services/transform.js) in line 4.

This `const Repository = require('imdone-core/lib/Repository')`
should be `const Repository = require('imdone-core/lib/repository')` (lower case `repository`)

**Comment by piascikj** [comment]
Just published a fix.  Thanks!!!

**Comment by dwuttke90** [comment]
thx alot man ;)
