### ISSUE TITLE
imdone task board not opening

### ISSUE THREAD

**Issue by wishnoo** [imdone/imdone-atom#379]
the imdone taskboard is not opening but the journal opens up? Any solution for this.

**Comment by piascikj** [comment]
Can you open "developer tools" from the View>Developer menu and check for errors?
Can you send some screenshots?

**Comment by wishnoo** [comment]
Sure Is this the console error you were looking for?
![atom imdone errors](https://user-images.githubusercontent.com/5163851/39978472-c3a770de-570e-11e8-9507-8623f95bf4a7.JPG)

**Comment by wishnoo** [comment]
![atom imdone errors](https://user-images.githubusercontent.com/5163851/39978562-402bf54e-570f-11e8-91f2-f9606482219c.JPG)

**Comment by piascikj** [comment]
Looks like I forgot to added a dev dependency when it should have been a dependency.  This is fixed in 2.4.26.

**Comment by wishnoo** [comment]
okay thanks . I did update and now its working fine.

**Comment by piascikj** [comment]
Excellent!
