### ISSUE TITLE
imDone not picking up Tasks from todo.txt in project root directory?

### ISSUE THREAD

**Issue by Sam2304** [imdone/imdone-atom#40]
First off, thanks so much for this plugin, its awesome!

Not sure if I've managed to misconfigure something or something, but I've added a todo.txt file to my project root directory (to look after tasks that don't have a home in my code yet), but for some reason none of the tasks in there (defined using #TODO) are picked up by imdone.

I've tried making the file a code file (.js to match the rest of my code), but to no avail.

I get the feeling I'm being stupid...?

**Comment by piascikj** [comment]
Hi Sam,  Thanks for the compliment.  Are you defining your tasks with a sort?  A task that's not in a code file should look like this...
`#TODO:1 Do something`

or like this

`[Do something](#TODO:1)`

**Comment by Sam2304** [comment]
Ah bugger.  Yup, that sorted it!  All showing up now.

Sorry I must have missed that in the Docs!

**Comment by piascikj** [comment]
Great! :smiley_cat:
