### ISSUE TITLE
bad integration with themes.

### ISSUE THREAD

**Issue by akaRem** [imdone/imdone-atom#44]
you may have any theme: red, green, white, but these panels will retain their colors

<img width="645" alt="2015-11-18 22 03 49" src="https://cloud.githubusercontent.com/assets/1472728/11251057/92d39242-8e40-11e5-824b-2642c1311223.png">

**Comment by akaRem** [comment]
looks awkward

**Comment by piascikj** [comment]
what theme are you using?  And what version of imdone-atom?

**Comment by akaRem** [comment]
Mostly i'm using `Atom Material` + `Atom Material`
and it looks like this:
<img width="498" alt="2015-11-18 23 08 40" src="https://cloud.githubusercontent.com/assets/1472728/11252868/7861d30c-8e49-11e5-8b9e-76d880dcbf67.png">

It would be cool if it will look like this:
<img width="657" alt="2015-11-18 23 10 05" src="https://cloud.githubusercontent.com/assets/1472728/11252890/95ce816a-8e49-11e5-8c34-0fd9c9c4fc94.png">

$ apm list | grep imdone
├── imdone-atom@1.2.1
$ atom --version
1.2.1

**Comment by akaRem** [comment]
Better.

<img width="644" alt="2015-11-19 23 36 00" src="https://cloud.githubusercontent.com/assets/1472728/11283545/535180e4-8f16-11e5-80c5-11fdacb55425.png">
<img width="671" alt="2015-11-19 23 35 44" src="https://cloud.githubusercontent.com/assets/1472728/11283548/585ad018-8f16-11e5-88ac-41f1271960b2.png">

$ apm list | grep imdone
├── imdone-atom@1.2.3
 atom --version 
1.2.2

**Comment by akaRem** [comment]
icon doesn't match with most popular iconset:
![Uploading Снимок экрана 2015-11-19 в 23.43.14.png…]()

 $ apm list | grep icon  
├── file-icons@1.6.12

**Comment by akaRem** [comment]
these icons don't match too. :(

<img width="272" alt="2015-11-19 23 47 22" src="https://cloud.githubusercontent.com/assets/1472728/11283909/04393374-8f18-11e5-9893-a02f83990991.png">

<img width="323" alt="2015-11-19 23 47 48" src="https://cloud.githubusercontent.com/assets/1472728/11283902/fd7bd5be-8f17-11e5-85ff-0f3168fe1c65.png">

I think their appearance should match with icons from core UI components which do similar things.
In my case
- "+" sign instead of "1/2" icon
- gear instaed of tools
- another 'x' sign
- "filter tasks", but in Atom for the same kind of input "search packages" is used (with no 'x')
