### ISSUE TITLE
Keybinding conflict

### ISSUE THREAD

**Issue by samirfor** [imdone/imdone-atom#46]
Hello,

I do not know if this is an issue but the <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>T</kbd> shortcut is already used by the Atom core.

![screenshot - 24-11-2015 - 08 41 22](https://cloud.githubusercontent.com/assets/2769423/11365729/2916d882-9287-11e5-9a4c-6316e20cd4d3.png)

Would not it be better to change it?

**Comment by Sam2304** [comment]
A lot of plugins seem to conflict with one another and atom itself, my experience generally suggests its up to the user to choose which key bindings they want to use in their keymap file.  I don't tend to use the `re-open last` command much (I can always reach it using the command palette if I like), as I tend to use `ctrl+t` to jump to a file directly, even if I've just closed it.

If I decided I wanted to re-assign Imdone and use the original command for the current shortcut, I can do that in the keymap file.

My keymap at the moment looks like this:
![screenshot from 2015-11-24 11 49 24](https://cloud.githubusercontent.com/assets/3308997/11365863/74f36d3c-92a1-11e5-95f1-94e1807b51d6.png)

Trying to find a non-conflicting keybinding would be a bit tricky.  If a specific user has a conflict, its straightforward to re-assign it.

Hope that answers your query?

**Comment by samirfor** [comment]
Yes! I already done that. I'm using <kbd>Ctrl</kbd>-<kbd>Alt</kbd>-<kbd>Shift</kbd>-<kbd>T</kbd>.
I just opened this issue by find it strange to use a combination already in use.

Thanks for the quick response.

**Comment by Sam2304** [comment]
No worries, I know the feeling, roughly half the plugins I use seem to conflict with each other or Atom Core...

**Comment by piascikj** [comment]
I'll be changing the binding to Alt-T in the next release.

**Comment by filjoseph1989** [comment]
Just used crtl+shift+p either,
