### ISSUE TITLE
filtering tasks could show number of matches

### ISSUE THREAD

**Issue by jronallo** [imdone/imdone-atom#50]
When you filter tasks in the tools side menu, each of the task lists could show the number of matching tasks (as well as the current number of all tasks on the list). This could be done in two possible places. First the filter match count could be included in the tools menu on the lines where visibility for a list can be triggered. It could also be that the task list headers on the board could show both the number of tasks in that list as well as how many match the current filter.

**Comment by piascikj** [comment]
+1

**Comment by piascikj** [comment]
I like this idea.  If you're interested, would you like to take a stab at coding it?

**Comment by jronallo** [comment]
@piascikj I would be interested in giving it a shot, but will not be free to try until the holidays.

**Comment by piascikj** [comment]
@jronallo I'm working on it now.  Better late than never right!  I'm implementing it now because I'm also adding a delete all visible tasks button and a replace feature.

**Comment by piascikj** [comment]
This is in the latest release.
