### ISSUE TITLE
zap feature opens more files than displayed

### ISSUE THREAD

**Issue by jronallo** [imdone/imdone-atom#53]
The zap feature is a really great addition, but it seems to open up way more files than are actually filtered down to. I can do a search that filters down to 3 tasks, then clicking the zap button opens up at least 10 files.

**Comment by piascikj** [comment]
I think I got this one figured out.  I'll have it fixed up in a few minutes.

On Wed, Dec 2, 2015 at 8:47 AM, Jason Ronallo <notifications@github.com>
wrote:

> The zap feature is a really great addition, but it seems to open up way
> more files than are actually filtered down to. I can do a search that
> filters down to 3 tasks, then clicking the zap button opens up at least 10
> files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/imdone/imdone-atom/issues/53>.
>



-- 
*Jesse Pia**ś**cik*
Founder @imdoneIO <https://twitter.com/imdoneIO> | imdone.io
about.me/jesse.piascik
Expert mentor at Codementor.io
www.codementor.io/codewrangler
