### ISSUE TITLE
Ignoring paths

### ISSUE THREAD

**Issue by iansoper** [imdone/imdone-atom#6]
How do you make imdone ignore paths? (bower, npm are the main culprits showing a bunch of todos that aren't related to my projects)

**Comment by iansoper** [comment]
I just figured out that it is ignoring some paths, but not when my bower_components folder is in a different location than the root of the project. It would be nice to follow the "Exclude VCS ignored paths" setting in the global options.

**Comment by piascikj** [comment]
I agree, that would be nice, but in the meantime, You can ignore paths by adding to the exclude array in .imdone/config.json.  It should be in the root of your project.

**Comment by roman01la** [comment]
:+1:  `.imdoneignore` or something would be nice

**Comment by piascikj** [comment]
Thanks for the suggestion guys!  Just published v1.1.17 with .imdoneignore support!

**Comment by amiuhle** [comment]
I just did `ln -s .gitignore .imdoneignore`

**Comment by piascikj** [comment]
@iansoper imdone-atom now has it's own setting "Exclude VCS ignored paths".  I decided against the global setting because it's not recommended to rely on settings that aren't in your package.  Thanks for the suggestion!

**Comment by iansoper** [comment]
@piascikj That's great, I'll try it out.
