### ISSUE TITLE
Meta links not displaying

### ISSUE THREAD

**Issue by benfunkhouser** [imdone/imdone-atom#60]
Hi,

I like the meta feature (http://blog.imdone.io/post/111622263565/imdone-is-meta) but for some reason when I try using it everything works except for the link... no errors are thrown, the link icon just isn't displayed:

![image](https://cloud.githubusercontent.com/assets/8867474/11883152/b94363d0-a4c5-11e5-9b83-1c85462eabeb.png)

Thanks!

**Comment by piascikj** [comment]
Do you have it configured in .imdone/config.json?

**Comment by benfunkhouser** [comment]
Yes - I'm actually just trying to use the meta descriptors that you have included by default.  In this case I'm trying to use the user to construct the github link:

Here is the meta json from the .imdone/config.json
"meta": {
    "user": {
      "urlTemplate": "https://github.com/%s",
      "titleTemplate": "github profile for %s"
    },
    "issue": {
      "urlTemplate": "https://github.com/imdone/imdone-atom/issues/%s",
      "titleTemplate": "github issue #%s"
    }
}

Here is my todo item:
#TODO:10 Fill out description upon new task creation user:10101

**Comment by piascikj** [comment]
I can't seem to reproduce it.  Can you post your full config.js file?

**Comment by benfunkhouser** [comment]
Hmm... it could be an odd Windows-related bug.  I am using the default config.json file (haven't edited it)

**Comment by benfunkhouser** [comment]
{
  "exclude": [
    "^(node_modules|bower_components|\\.imdone|target|build|dist|logs)[\\/\\\\]?|\\.(git|svn|hg|npmignore)|\\~$|\\.(jpg|png|gif|swp|ttf|otf)$"
  ],
  "watcher": true,
  "code": {
    "include_lists": [
      "TODO",
      "DOING",
      "DONE",
      "PLANNING",
      "FIXME",
      "ARCHIVE",
      "HACK",
      "CHANGED",
      "XXX",
      "IDEA",
      "NOTE",
      "REVIEW"
    ]
  },
  "lists": [
    {
      "name": "CHANGED",
      "hidden": true
    },
    {
      "name": "BACKLOG",
      "hidden": true
    },
    {
      "name": "TODO",
      "hidden": false
    },
    {
      "name": "DOING",
      "hidden": false
    },
    {
      "name": "READY",
      "hidden": true
    },
    {
      "name": "DONE",
      "hidden": true
    }
  ],
  "marked": {
    "gfm": true,
    "tables": true,
    "breaks": false,
    "pedantic": false,
    "smartLists": true,
    "langPrefix": "language-"
  },
  "meta": {
    "user": {
      "urlTemplate": "https://github.com/%s",
      "titleTemplate": "github profile for %s"
    },
    "issue": {
      "urlTemplate": "https://github.com/imdone/imdone-atom/issues/%s",
      "titleTemplate": "github issue #%s"
    }
  }
}

**Comment by benfunkhouser** [comment]
![image](https://cloud.githubusercontent.com/assets/8867474/11910803/3d4d7d38-a5b5-11e5-873c-4828439f2a53.png)

**Comment by piascikj** [comment]
Are you editing the correct .imdone/config.json?  The one you should edit is in [Your project folder] > .imdone > config.json

**Comment by benfunkhouser** [comment]
Oh, you're right.  I can't believe I missed that!  It works great now that I'm editing the right json file :)  Thanks again for your work on this package.
