### ISSUE TITLE
Imdone Atom: Tasks does nothing at all

### ISSUE THREAD

**Issue by zachphillips** [imdone/imdone-atom#61]
I've tried leaving the TODOs in every syntax documented.

The .imdone config is all in the same directory of markdown, fountain, and txt files, all default.

No window opens.

**Comment by arjendk** [comment]
Same here... Atom 1.3.1 on Linux. Ctrl-shift-T shows imdone-atom:tasks in the keybinding resolver but nothing happens. I can't find a command through the command palette.

**Comment by piascikj** [comment]
imdone-atom opens in the context of a project.  Do you have a project open?

**Comment by DiaaFares** [comment]
@piascikj I'm trying to add TODOs in all available syntax but its not working for me!

**Comment by zachphillips** [comment]
Jesse, I do have a project open. You are talking in the context of the project-manager package?

I have a project with one folder and lots of files with TODOs in them. Nothing.

**Comment by piascikj** [comment]
@zachphillips Yes, they are one in the same.  Have you tried the project folder context menu > imdone- Show Tasks?

**Comment by zachphillips** [comment]
Okay, that worked… So what exactly is going on? You just can’t use command palette the first time you run it?

**Comment by zachphillips** [comment]
Ah, and the only way to update it still is to close it and reopen it from the contextual menu. It doesn’t update live.

Could it have to do with another package I have installed? The only other one I feel like could be affecting it is the nvAtom package, but I tried disabling it and nothing changed.

**Comment by piascikj** [comment]
@zachphillips Not sure what's going on.  I wasn't able to reproduce it.  What OS are you on?

**Comment by zachphillips** [comment]
El Capitan 10.11.2.

Here’s a video where you can see the issue in action: http://d.pr/v/1dOgf

If I manually give it a search order assignment, it will show up once I interact with the board. If I don’t give it an assignment, it will never show up, even if I activate imdone manually from contextual menu or command palette, as you can see there.

Either way, whether I assign an order or not, nothing is happening automatically.

Hope this helps.

**Comment by piascikj** [comment]
@zachphillips Thanks for the video.  Nice to see you use droplr too!  From what I can tell in the video, the tasks aren't showing because the [hash style](https://github.com/imdone/imdone-core#hash-style) and [markdown style](https://github.com/imdone/imdone-core#markdown-style) require a sort number.  That doesn't explain the lack of update after saving the file, but it could have been in the process of updating when you moved the task.  imdone-core uses it's own file watchers.  I might consider changing those task types to allow tasks without a sort number, but I would still want to keep the `:` to differentiate plain markdown links from tasks.

**Comment by piascikj** [comment]
@zachphillips , I'd be willing to troubleshoot further in a hangout.  Let me know your availability via email if you're interested.

**Comment by DiaaFares** [comment]
@piascikj I'm trying to add TODOs in all available syntax but its not working for me!

**Comment by piascikj** [comment]
@DiaaFares Can you post some examples?  IncludeTODO's and file names.

**Comment by zachphillips** [comment]
That would be tremendous Jesse, thanks!

My email is z@zach.be. Not sure where to find yours or I'd have reached out directly there.

Zach

**Comment by DiaaFares** [comment]
@piascikj I don't know what kind of examples you want, but I will try to explain:
I open new project then I create new file or open any existing file, I try to add TODOs with all available syntax
```
// TODO This is a task
// TODO: This is a task
// TODO:5 This is a task

#TODO:0 This is a task
#to-do:0 This is a task
[This is a task](#todo:10)
```


 but nothing happen! I didn't find any of these TODOs in the imdone page!

**Comment by piascikj** [comment]
@DiaaFares What is the file extension of the file these tasks are in?

**Comment by DiaaFares** [comment]
@piascikj php

**Comment by piascikj** [comment]
@DiaaFares and what os are you using?

**Comment by MarkRobbins** [comment]
These issues sound similar to mine - no auto-refresh of board on file save and not being able to activate/launch except from a 'system' tab (cannot ctrl-shift-t from editor). I am on windows 7 and available for debugging if you wish.

**Comment by piascikj** [comment]
The trouble seems to be with the file listener package I'm using.  It's not getting compiled correctly on some systems.  I'll be working on a fix over the next few days that will use the file listener support in atom.

**Comment by kabircse** [comment]
I am facing the same problem.
