### ISSUE TITLE
unable to install 1.3.18

### ISSUE THREAD

**Issue by jronallo** [imdone/imdone-atom#65]
Atom 1.3.2 and 1.3.3 on Xubuntu 15.10.

Here's the output:

> runas@3.1.1 install /tmp/apm-install-dir-116010-5697-egeeus/node_modules/imdone-atom/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-116010-5697-egeeus/node_modules/imdone-atom/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:90: recipe for target 'Release/obj.target/runas/src/main.o' failed
make: Leaving directory '/tmp/apm-install-dir-116010-5697-egeeus/node_modules/imdone-atom/node_modules/pathwatcher/node_modules/runas/build'

../src/main.cc:1:17: fatal error: nan.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.2.0-23-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-116010-5697-egeeus/node_modules/imdone-atom/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@1.0.6
npm ERR! Linux 4.2.0-23-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/jnronall/.atom/.apm/.apmrc" "--userconfig" "/home/jnronall/.atom/.apmrc" "install" "/tmp/d-116010-5697-1jpavml/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116010-5697-egeeus/npm-debug.log

**Comment by jronallo** [comment]
I get the same error when running: `apm install imdone-atom@1.3.17` so it seems as if the issue was introduced with that version. 

If anyone else has this issue you can install an older version with:
`apm install imdone-atom@1.3.16` which is currently the last version that works for me.

**Comment by piascikj** [comment]
I was afraid this might happen.  Strange thing is.  The library in question "pathwatcher" is an atom project library.  I implemented it for file watching over chokidar because chokidar was causing problems for some.  I have one more alternative to try, and it doesn't require an ndoe-gyp build.  I should have it up and running by tomorrow.

**Comment by jronallo** [comment]
I was able to upgrade to 1.3.19.

**Comment by piascikj** [comment]
@jronallo That's great!  How is it working for you?

**Comment by jronallo** [comment]
@piascikj So far, so good. Thanks.
