### ISSUE TITLE
Optionally hide tasks that have been completed

### ISSUE THREAD

**Issue by igoldin2u** [imdone/imdone-atom#68]
If a task has a completed date in todo.txt syntax (e.g., `x 2015-02-09`), either hide these tasks by default, or give them a separate (bottom of screen) sort order.

**Comment by semka** [comment]
Really miss this feature

**Comment by kelserj** [comment]
I think adding a filter to the "DONE" column that allows the user set the history they see. I am guessing this is part of the archive feature but I can see the two working separately. 

I want to see the past weeks worth of tasks completed but may only want to archive once a month. After 10 days I would like the done tasks to not show.

**Comment by piascikj** [comment]
There's a feature in [imdone desktop](https://imdone.io) that does this.
