### ISSUE TITLE
PDFs now showing up in 1.3.20

### ISSUE THREAD

**Issue by jronallo** [imdone/imdone-atom#70]
After updating to 1.3.20 and restarting I'm now seeing some new task columns that are filled only with PDFs. I did not change my .imdone/config.json file.

**Comment by piascikj** [comment]
Do you have an example?

**Comment by jronallo** [comment]
Columns and tasks like these were not showing up before.

![screenshot_2016-01-13_21-00-05](https://cloud.githubusercontent.com/assets/66485/12313792/b5ad825e-ba38-11e5-85e0-b9934dfb3c43.png)

**Comment by piascikj** [comment]
When you click on the line in the file, does it look like a task?

**Comment by jronallo** [comment]
No, it just looks like more UTF8 replacement characters, but maybe you'll see something I don't. 

![screenshot_2016-01-14_08-31-33](https://cloud.githubusercontent.com/assets/66485/12325582/3bf4b3b8-ba99-11e5-8d9b-db55226c2868.png)

**Comment by jronallo** [comment]
Adding pdf to "exclude" in .imdone/config.json resolves this, but I'm not sure why they were showing up now but hadn't been before.

**Comment by piascikj** [comment]
I just updated imdone-core with better binary checking.  It's now catching pdfs.  I'm not sure what happened, but now it's fixed up and will be in imdone-atom 1.3.21 in  just a minute.
