### ISSUE TITLE
Slow Startup

### ISSUE THREAD

**Issue by iev6** [imdone/imdone-atom#77]
imdone-atom crashes atom while startup.
timecop says, imdone-atom added 4606ms to startup time

**Comment by piascikj** [comment]
Have you tried using .imdoneignore?

**Comment by iev6** [comment]
I only have ~10 or so files in the folder where imdone is active, all of
which are source files, so I haven't used it.

*Giridhur S *
Undergraduate Junior
Electrical Engineering
Indian Institute of Technology,Madras

**Comment by pleonex** [comment]
The start-up time can be decreased by *requiring* the modules inside the functions instead of globally. In the case of a function is called many times, probably it's better to *require* it from the activate function to load it just one time.
