### ISSUE TITLE
Items disappear

### ISSUE THREAD

**Issue by zimt28** [imdone/imdone-atom#79]
When list names contain lowercase letters or numbers, items disappear. Dashes and underscores work.
I'm on Mac `v10.11.2`, Atom `v1.5.4`.

**Comment by piascikj** [comment]
If you're try putting a # in front of your list name.  If you use a # lower case is allowed.

**Comment by zimt28** [comment]
@piascikj That seems to work, but I feel like that should happen automatically, otherwise it's not possible to move items between lists using the UI.

**Comment by zimt28** [comment]
I think I can close this as there's already an issue here: https://github.com/imdone/imdone-core/issues/30

**Comment by piascikj** [comment]
@zimt28 This is fixed in 1.3.28
