### ISSUE TITLE
Journal-names

### ISSUE THREAD

**Issue by xeor** [imdone/imdone-atom#81]
<thanks>`imdone` almost hit a PERFECT hit on my current workflow. Looking very much forward to whats next!</thanks>

In the settings, it supports journal filenames based on text and one variable (`${DATE}`). Would it be, or is it in the pipeline to expand journal creations to support more advanced name-templates? Example, based on highlighed text, a popup to ask for part of the filenames, and so on.
I usually ends up taking a lot of notes during the day, all in the format "YYYY-MM-DD notename here.md".

**Comment by piascikj** [comment]
This looks like an interesting idea.  Not very urgent on the enhancement list for me though.  If you want to look at implementing this, I'd merge a pull request!

**Comment by piascikj** [comment]
I'm planning on implementing this in the next week.  I'll get my ideas on a wireframe and post them here.

**Comment by kelserj** [comment]
If this could use the tags, context or meta data you could create a log for a single issue. This would be very helpful and could begin to become an issue log/archive library.

**Comment by piascikj** [comment]
Issue closed with imdone.io by removing a comment.

----

https://github.com/imdone/imdone-atom/blob/729c88d5c2b7a6fe241f0f1eb2f94f821f463b3a/lib/imdone-atom.coffee#L193-L212
