### ISSUE TITLE
Hash and Markdown style not recognised on atom mac

### ISSUE THREAD

**Issue by maxpower9000** [imdone/imdone-atom#82]
Only the standard "// TODO" style tags are recognised in Atom on Mac.
Testing same code on my Windows 7 machine I found all styles to be found correctly.

**Comment by piascikj** [comment]
Can you send me a sample task that's not recognized, and the name of the file it's in?

**Comment by maxpower9000** [comment]
Working now. Don’t know why. Can’t recreate the original issue.
