### ISSUE TITLE
Extreme lag or freeze starting imdone in Atom on Mac

### ISSUE THREAD

**Issue by maxpower9000** [imdone/imdone-atom#83]
Starting imdone freezes/crashes Atom most of the time on my Mac.
Project size below 200 files.
.imdoneignore is used.

This is a recurring phenomenon and renders it useless.
Same (and bigger) projects on Windows 7 machine are being displayed within <2 seconds.

I LOVE imdone! Hope to find the reason for this behaviour.

**Comment by piascikj** [comment]
This is not good.  When did it start?  What kind of files are in the folders?  Are there large files, binary files, etc?

**Comment by maxpower9000** [comment]
No large files. No binary. I believe it's mostly to do with the amound of files in the tree. I dialed down to max 100 files. And tried a flater tree. Then it worked. I don’t know what’s the threshold, though.

Consider it done for now, since I don’t have the time for thorough testing.

Thanks for the AWESOME package!
