### ISSUE TITLE
Exclude specific files/directory or even a custom .ignore like file/config?

### ISSUE THREAD

**Issue by AngelsDustz** [imdone/imdone-atom#84]
Hello,
This isn't realy a bug but more a feature request.
I would really appriciate it if you could look into a file/directory
exclude option. Because right now I am using jQuery and what not. And they have a lot of TODO's I really am not intrested in seeing.

**Comment by artemruts** [comment]
Yes, this is exactly what we need, can you add this feature, please?
Maybe somethings like negation `!` operator? 

So we can use `.gitignore` style: 
```
path1/                           # ignore this directory and it's subdirectories
!path1/path2/important_stuff     # but include this one
```

Thank you!

**Comment by piascikj** [comment]
Have you tried using an [`.imdoneignore`](https://github.com/imdone/imdone-atom#ignoring-files) file?

**Comment by AngelsDustz** [comment]
When I first installed it it didn't show me the readme, it was after I restarted my client I saw and read the readme. So yeah...

Using the .imdoneignore and the config file in .imdone folder you can do this.
