### ISSUE TITLE
Board doesn't update with both normal & alternate watcher

### ISSUE THREAD

**Issue by aoozdemir** [imdone/imdone-atom#85]
I've tried both. It doesn't update. I have to close the board and open it again after every change. Also Atom crashes after a while when I changed something. (while updating the board, I guess).

**Comment by piascikj** [comment]
What OS are you running on?

**Comment by holbue** [comment]
I have the same problem. I'm running Windows 8.1

PS:  A refresh button would be a useful workaround, or also useful for people who don't want to monitor file changes for performance reasons...

**Comment by aoozdemir** [comment]
I'm on Windows 10 @piascikj. Sorry for the late response. I think this is still an issue. A refresh button is a good idea.

**Comment by dynobo** [comment]
I have the same problem. Also using Windows 8.1. I'm open to give you more input, if it helps.

**Comment by piascikj** [comment]
Is anyone still having this issue?

**Comment by aoozdemir** [comment]
Unfortunately, I stopped using Atom and move onto macOS. It has been a while. So, I'm not sure if this issue still persists. I'll try to get my hands on my old pc to test this out when I'm available.

Cheers,
Oguzhan

On 30 Dec 2017 20:48 +0300, Jesse Piascik <notifications@github.com>, wrote:

Is anyone still having this issue?
