### ISSUE TITLE
Wrong source links handling in issue view

### ISSUE THREAD

**Issue by jajakobyly** [imdone/imdone-atom#9]
I'm running iMDone-atom 1.1.10, Atom 1.05 on Windows 10.

In issue views, links to the source code in tasks point to wrong path. For example:
 -  When my project is located in `C:\Users\marek\foo` and TODO item is in `C:\Users\marek\foo\path\to\file.rs:143`
 -  iMDone generates following HTML task node:
    
    ```html
    <li class="task well" data-path="path\to\file.rs" draggable="false" id="48c8af22f1a08be36077292dfd5a3ae2a4372557">
        <!-- ... -->
        <div class="task-source">
            <a class="source-link" data-line="143" data-uri="\Users\marek\foo\path\to\file.rs" draggable="false" title="go to task source">path\to\file.rs:143</a>
        </div>
    </li>
    ```
 -  And after click it tries to open `C:\Users\marek\foo\Users\marek\foo\path\to\file.rs`.

**Comment by piascikj** [comment]
@jajakobyly I think we've got this handled.  Let me know if it's working ok for you and I'll close out the ticket

**Comment by jajakobyly** [comment]
iMDone 1.1.12, behaviour didn't change. I'll try to prepare simple demo
