### ISSUE TITLE
custom tag creation

### ISSUE THREAD

**Issue by lordlabakdas** [imdone/imdone-atom#91]
is it possible to create and keep track of custom tags such as `MYTODO`? The reason am asking is my repo is from a forked base which has `TODOs` and populates my list. Adding `.imdoneignore` seems to modify the respective files.
Is there an alternate solution for this scenario?

**Comment by edjroot** [comment]
I recorded a GIF to illustrate what you have to do. I hope this helps.

(Notice that I had to close and reopen the page to see the tracked files. I'm opening an issue to see if this gets fixed.)

![custom todo tag creation](https://cloud.githubusercontent.com/assets/3580075/15130038/19e21764-161c-11e6-97c9-730185cee2c0.gif)

**Comment by lordlabakdas** [comment]
Works like a charm. Thank you!
I did not have to close the page. All I did was add the example comment and calls tasks from the command palette, and it appeared.

**Comment by edjroot** [comment]
You're welcome!

> I did not have to close the page. All I did was add the example comment and calls tasks from the command palette, and it appeared.

Oh, I didn't think of that. Shame on me. Anyways, I already opened the other issue, so let's see how it goes.

**Comment by lordlabakdas** [comment]
Want to take this opportunity to say its a wonderful package, very helpful :)
Thank you for the package and the support
