### ISSUE TITLE
Automatically load task list from newly created tokens

### ISSUE THREAD

**Issue by edjroot** [imdone/imdone-atom#92]
Maybe this is intentional, but imdone's tasks page doesn't get updated when files are changed right after I create a custom token. This GIF illustrates that: I have to close and reopen the tab to see the changes. (Edit: Another user in #91 said it's also possible to update the page by just issuing `imdone` again, but it didn't work here. I'm using Ubuntu 16.04.)

![custom todo token creation](https://cloud.githubusercontent.com/assets/3580075/15130038/19e21764-161c-11e6-97c9-730185cee2c0.gif)

Wouldn't it be desirable to change such behavior?

**Comment by piascikj** [comment]
Sorry I'm just getting back to you now, but I think this can be fixed easily, so I'll look at putting it into the next release.  I have to make sure to update the `.imdone/config` > **code.include_lists** property with your custom tag and call **repository.refresh(cb)**.  Shouldn't be too much trouble for the next release.

**Comment by edjroot** [comment]
No worries. Thanks!

**Comment by piascikj** [comment]
This should be fixed in 2.0
