### ISSUE TITLE
Parse multiline TODOs

### ISSUE THREAD

**Issue by edjroot** [imdone/imdone-atom#93]
I always try to be concise, but sometimes a longer TODO comment is needed. Is there a way to show a multiline comment in the task list? This would probably require some extra symbol to tell imdone it should concatenate the lines (e.g. a backwards slash at the end of the line, as in Python), but it seems perfectly feasible anyway.

**Comment by piascikj** [comment]
I like this one too! :+1:

**Comment by kelserj** [comment]
I think some form of delimiter could be used here. Perhaps /#TODO or something at the end of the texts to include. I find this concept useful for keeping the context of the todo together. A gist option would be a nice touch with a more or peek gui. Also have seen longer comments added in tool tip or hover over pop up.

**Comment by piascikj** [comment]
Just finished this one.  The way imdone terminates a multiline comment in a code file is when it encounters another TODO or a line that does not contain a comment.  In markdown or plain text multiline comments terminate when imdone finds a blank line or another line with a task.
